name: Deploy CI/CD

on: 
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.15.3]

    steps:
    - name: Docker Build and Deploy to Heroku
      uses: actions/checkout@v2
      uses: akhileshns/heroku-deploy@v3.0.0
      with:
        heroku_api_key: ${{secrets.HEROKU_TOKEN}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}        
        usedocker: true
