name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.15.3]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
    - name: fix code coverage paths
	    working-directory: ./coverage
	    run: |
	      sed -i 's/\/home\/runner\/work\/pre-xend\/pre-xend\//\/github\/workspace\//g' lcov.info
	      sed -i 's/\/home\/runner\/work\/pre-xend\/pre-xend\//\/github\/workspace\//g' sonar-cloud-reporter.xml
        
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
