name: Sonar Analysis

on: 
  push:
    branches:
      - deploy

jobs:
  build:

    runs-on: ubuntu-latest

    steps:        
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
